features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: themes/custom/khalsasecurity/khalsasecurity.png
favicon:
  use_default: 0
  path: themes/custom/khalsasecurity/favicon.ico
  mimetype: image/vnd.microsoft.icon
header: ''
fixed_header: 1
scrolltop: ''
scrolltop_display: 1
bootstrap_remote_type: cdn
premium_description: ''
